### ISSUE TITLE
新手求教！！

### ISSUE THREAD

**Issue by Yuannbo** [greyli/sayhello#11]
新手求教，我复制粘贴过来一样的代码报了下面的错误

![image](https://user-images.githubusercontent.com/37706565/56097291-cdef8a80-5f24-11e9-898b-fa5c9b4e6894.png)

找了半天原因感觉似乎是bootstrap里并没有form.html

![image](https://user-images.githubusercontent.com/37706565/56097325-1f981500-5f25-11e9-9bc0-569a053957d1.png)

那个render_form在那个form.py文件里，请问这时候该怎么调用。

**Comment by yukuaifeng** [comment]
我好像并没有遇到这样的问题，也许使用pip install的方式来安装这个bootstrap-flask库会好一点，安装命令是 pip install flask_bootstrap

**Comment by greyli** [comment]
这个项目使用的是 Bootstrap-Flask，而不是 Flask-Bootstrap。正确的安装命令是：
```
pip install bootstrap-flask
```
下次有和项目源码无关的问题请发到 [HelloFlask 仓库](https://github.com/greyli/helloflask)或 [HelloFlask 论坛](https://discuss.helloflask.com)。
