### ISSUE TITLE
在pycharm上部署该项目，在view模块报错

### ISSUE THREAD

**Issue by SaHaes** [greyli/sayhello#13]
AssertionError: View function mapping is overwriting an existing endpoint function: index
这是编译器的报错，可是整个项目中只有一个index函数，尝试了很多方法都没解决，求助。

**Comment by greyli** [comment]
请提供完整代码。

**Comment by huohuoryan** [comment]
辉哥，你好
我也出现了同样的问题，代码就是拷贝你github上views.py里的代码，若单独执行就会出现AssertionError: View function mapping is overwriting an existing endpoint function: index
还有一个问题，就是7.7.2我认为讲的不够详细，我有些不懂。比如实例文件夹怎么加入到.gitignore中，如何确保不会提交到Git仓库中？

**Comment by huohuoryan** [comment]
> 请提供完整代码。

辉哥，你好
我也出现了同样的问题，代码就是拷贝你github上views.py里的代码，若单独执行就会出现AssertionError: View function mapping is overwriting an existing endpoint function: index
还有一个问题，就是7.7.2我认为讲的不够详细，我有些不懂。比如实例文件夹怎么加入到.gitignore中，如何确保不会提交到Git仓库中？

**Comment by greyli** [comment]
「单独执行」是什么意思？你是怎么运行程序的？

**Comment by huohuoryan** [comment]
> 「单独执行」是什么意思？你是怎么运行程序的？

在pycharm中，单独运行views.py

**Comment by huohuoryan** [comment]
> Flask 程序不能这样运行。对于这个项目来说，你需要在项目根目录执行 flask run 命令（确保安装了所有依赖）。

好的，感谢辉哥
我是初学者，日后有问题再请教你
