### ISSUE TITLE
分支切换到Bootstrap 的tag时 flask run 出现了错误

### ISSUE THREAD

**Issue by opaser** [greyli/sayhello#15]
TypeError: environment can only contain strings

**Comment by greyli** [comment]
其他分支下执行 flask run 不报错？另外，麻烦给出操作系统及版本、Python 版本。

**Comment by greyli** [comment]
先关闭了，后续有问题可以继续评论或重开。另外建议尝试更新 python-dotenv 版本：
```
$ pip install -U python-dotenv
```
