### ISSUE TITLE
Invalid package

### ISSUE THREAD

**Issue by dispyfree** [greyli/sayhello#27]
Hi!

requirements.txt lists mako==1.1.13 as a dependency - this version simply doesn't exist on pypi. Works like a charm after changing this to any valid version.
Also, werkzeug is outdated and fails on Python3.9; updating its version to werkzeug==0.15.5 helps.

Cheers,

**Comment by greyli** [comment]
You may post to the wrong place, the requirements.txt in this repo does not contain `mako`.

**Comment by dispyfree** [comment]
You're right - it was supposed to go in flask-examples; [I've raised an issue there](https://github.com/greyli/flask-examples/issues/7).

Thx for the quick reply!
