### ISSUE TITLE
感觉书中有几个错误，还请核对

### ISSUE THREAD

**Issue by Varpc** [greyli/sayhello#5]
![image](https://user-images.githubusercontent.com/29668118/48314911-1b309e80-e60b-11e8-8ffe-8c4b9beebbd5.png)
7.2.3节，感觉这里的sayhello.py应为models.py,这里与下文矛盾
![image](https://user-images.githubusercontent.com/29668118/48314946-909c6f00-e60b-11e8-9fc0-47fbad6b467a.png)
7.3.2节，划线部分中的右括号应在full_path后

**Comment by greyli** [comment]
感谢反馈，这两个的确是错误，第一个是后期结构调整忘记修改，第二个是编辑人员改错了。这两处已经列在了[勘误列表](http://helloflask.com/book/errata/)里。最近书正在筹划重印，到时这些勘误会统一纠正并推送电子书更新。
