### ISSUE TITLE
flask forge Error: No such command "forge

### ISSUE THREAD

**Issue by baixiaoyu** [greyli/sayhello#8]
flask forge
Usage: flask [OPTIONS] COMMAND [ARGS]...

Error: No such command "forge".

**Comment by greyli** [comment]
猜测是依赖 faker 未安装，执行 `pipenv install --dev`。

**Comment by greyli** [comment]
Close for inactive. Please feel free to comment or reopen this issue.

**Comment by sanxincao** [comment]
i have the same problem

**Comment by liuchangyu666** [comment]
> Close for inactive. Please feel free to comment or reopen this issue.
你好 我买了你的书 第195页 留言板 那里 也有同样问题

**Comment by greyli** [comment]
@liuchangyu666 请问你有安装依赖 `faker` 吗？注意安装项目依赖的完整命令应该是 `pipenv install --dev`。

**Comment by liuchangyu666** [comment]
老师，我自己弄好了啦 是解释器跟虚拟环境的问题



在 2021-04-22 12:19:13，"Grey Li" ***@***.***> 写道：

@liuchangyu666 请问你有安装依赖 faker 吗？注意安装项目依赖的完整命令应该是 pipenv install --dev。
