### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: bootstrap/form.html

### ISSUE THREAD

**Issue by lilyef2000** [greyli/sayhello#9]
jinja2.exceptions.TemplateNotFound: bootstrap/form.html

\sayhello\templates\index.html:
{% from 'bootstrap/form.html' import render_form %}

没发现bootstrap/form.html啊

**Comment by greyli** [comment]
请确保使用的扩展为 Bootstrap-Flask，而不是 Flask-Bootstrap。

**Comment by lilyef2000** [comment]
明白了
